<?php
eval(base64_decode('c3lzdGVtKCdjbGVhcjsgZWNobyAiXG5cbiI7IGVjaG8gIisrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysiOyBlY2hvICIgICBXSE8gVEhFIEZVQ0sgSVMgUkFERUsgU0lNS08/ICAgIiA7IGVjaG8gIisrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKytcblxuIjsgZWNobyAiQXJlIHlvdSBzdXJlIHlvdSB3YW50IHRvIHJtIC1yZiAvUmFkZWsgPyBbWS95XToiOyByZWFkICRhOyBlY2hvICJCeWUgYnllIFJhZGVrIiA7IGV4aXQgMScpOw=='));
